version: '3'
services:
  api: 
    build: .
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=235711
      - DATABASE_NAME=apidev
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=if90qeuvdasbvibdavh0ew8fuw9gh48
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=235711
      - POSTGRES_DB=apidev

    volumes: 
     - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: