name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - names: pulling git repo
        uses: actions/checkout@v2
      - names: say hello
        run: echo 'Hi there!'
